/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tool/{tool-id}/scrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * tool 찜하기
         * @description tool을 찜하거나, 찜을 해제합니다.
         */
        post: operations["postToolScrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tool/{tool-id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * tool 좋아요
         * @description tool에 좋아요를 누르거나, 좋아요를 취소합니다.
         */
        post: operations["postToolLike"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 신고 생성
         * @description 게시글이나 댓글을 신고합니다.
         */
        post: operations["createReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notification/notice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 공지 발송(관리자)
         * @description 모든 사용자에게 공지를 발송합니다.
         */
        post: operations["notice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notification/block-notice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 커뮤니티 제한 공지 발송(관리자)
         * @description 커뮤니티가 제한된 사용자에게 공지를 발송합니다.
         */
        post: operations["blockNotice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 댓글 조회
         * @description 댓글을 조회합니다.
         */
        get: operations["getComment"];
        put?: never;
        /**
         * 댓글 작성
         * @description 댓글을 작성합니다.
         */
        post: operations["postComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 게시글 리스트 조회
         * @description 게시글 리스트를 조회합니다.
         */
        get: operations["getBoardList"];
        put?: never;
        /**
         * 게시글 작성
         * @description 게시글을 작성합니다.
         */
        post: operations["createBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/board/{board-id}/scrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 게시글 스크랩
         * @description 게시글을 스크랩합니다.
         */
        post: operations["scrapBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원 가입
         * @description 회원 가입을 진행합니다.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Access Token 재발급
         * @description Refresh Token을 통해 Access Token을 재발급합니다.
         */
        post: operations["reissueToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 로그아웃을 진행합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 소셜 로그인
         * @description 소셜 로그인에서 발급받은 Authorization Code를 통해, 로그인을 진행합니다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 관리자용 툴 추가
         * @description 관리자용 툴 추가 API입니다.
         *
         *     **플랜(plans) 필드 사용 가이드:**
         *     - 플랜은 여러 개를 추가할 수 있습니다 (배열 형태)
         *     - 각 플랜은 planName(플랜명), planPrice(가격), planDescription(설명)을 포함합니다
         *     - planType과 plans는 함께 사용됩니다:
         *     	* FREE: 무료 플랜인 경우 plans는 빈 배열이거나 무료 플랜 1개만 포함
         *     	* MONTHLY: 월간 구독 플랜들 (예: Basic, Pro, Enterprise 등)
         *     	* PURCHASE: 일회성 구매 플랜들 (예: Starter, Professional 등)
         *     	* MONTHLY_ANNUAL: 월간 & 연간 플랜 혼합 (예: 월간 Basic, 연간 Basic 등)
         *
         *     **플랜 케이스 예시:**
         *     1. 무료 툴: planType="무료", plans=[]
         *     	또는 plans=[{planName:"무료", planPrice:0, planDescription:"기본 기능 무료 제공"}]
         *     2. 월간 구독: planType="월간",
         *     	plans=[{planName:"Basic", planPrice:10000, ...}, {planName:"Pro", planPrice:30000, ...}]
         *     3. 일회성 구매: planType="구매",
         *     	plans=[{planName:"Starter", planPrice:50000, ...},
         *     	{planName:"Professional", planPrice:150000, ...}]
         *     4. 혼합: planType="월간 & 연간",
         *     	plans=[{planName:"Basic 월간", planPrice:10000, ...},
         *     	{planName:"Basic 연간", planPrice:100000, ...}]
         *
         *     **주의사항:**
         *     - planPrice는 원화 단위로 입력합니다 (예: 10000 = 1만원)
         *     - planName, planPrice, planDescription은 모두 필수입니다
         *     - planDescription은 최대 500자까지 입력 가능합니다
         *     - plans가 null이거나 빈 배열일 수 있지만, planType이 설정된 경우 적절한 플랜 정보를 제공하는 것을 권장합니다
         */
        post: operations["createTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로필 조회
         * @description 사용자의 프로필을 조회합니다.
         */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 프로필 수정
         * @description 사용자의 프로필을 수정합니다.
         */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/v1/reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 신고 처리
         * @description 관리자가 신고를 처리합니다. (승인/거절 및 제재 적용)
         */
        patch: operations["processReport"];
        trace?: never;
    };
    "/api/v1/notification/read/{notification-id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 알림 읽음
         * @description 알림을 읽음 처리 합니다.
         */
        patch: operations["readNotification"];
        trace?: never;
    };
    "/api/v1/board/{board-id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 게시글 조회
         * @description 게시글을 조회합니다.
         */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        /**
         * 게시글 삭제
         * @description 게시글을 삭제합니다.
         */
        delete: operations["deleteBoard"];
        options?: never;
        head?: never;
        /**
         * 게시글 수정
         * @description 게시글을 수정합니다.
         */
        patch: operations["updateBoard"];
        trace?: never;
    };
    "/api/v1/admin/tools/{toolId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 관리자용 툴 삭제
         * @description 관리자용 툴 삭제 API입니다.
         */
        delete: operations["deleteTool"];
        options?: never;
        head?: never;
        /**
         * 관리자용 툴 수정
         * @description 관리자용 툴 수정 API입니다.
         *
         *     **플랜(plans) 필드 수정 가이드:**
         *     - plans 필드를 전송하면 기존 플랜들이 모두 삭제되고 새로운 플랜들로 교체됩니다
         *     - plans를 null로 보내면 플랜 정보는 변경되지 않습니다
         *     - plans를 빈 배열([])로 보내면 모든 플랜이 삭제됩니다
         *
         *     **플랜 수정 케이스:**
         *     1. 플랜 추가/변경: plans=[{planName:"New Plan", planPrice:20000, planDescription:"새로운 플랜"}]
         *     2. 플랜 삭제: plans=[] (모든 플랜 삭제)
         *     3. 플랜 유지: plans=null (기존 플랜 그대로 유지)
         *     4. 플랜 수정: plans=[수정된 플랜 목록] (기존 플랜 삭제 후 새로 추가)
         *
         *     **주의사항:**
         *     - 플랜 수정 시 planName, planPrice, planDescription은 모두 필수입니다 (null이면 해당 플랜은 저장되지 않습니다)
         *     - planDescription은 최대 500자까지 입력 가능합니다
         *     - planType도 함께 수정하려면 planType 필드도 함께 전송하세요
         *     - 기존 플랜을 유지하면서 일부만 수정하려면, 유지할 플랜도 포함하여 전체 플랜 목록을 다시 전송해야 합니다
         */
        patch: operations["updateTool"];
        trace?: never;
    };
    "/api/v1/user/scrap-tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 찜한 툴 목록 조회
         * @description 사용자의 찜한 툴 목록을 조회합니다.
         */
        get: operations["getFavoriteTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/scrap-boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 스크랩 글 목록 조회
         * @description 스크랩 글 목록을 조회합니다.
         */
        get: operations["getScrapBoards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 닉네임 중복 확인
         * @description 닉네임 중복을 검사합니다.
         */
        get: operations["checkDuplicate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 작성한 게시글 목록 조회
         * @description 사용자가 작성한 게시글 목록을 조회합니다.
         */
        get: operations["getUserBoards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * tool 목록 조회
         * @description tool의 목록을 조회합니다.
         */
        get: operations["getToolList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tool/{tool-id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * tool 세부정보 조회
         * @description tool의 세부정보를 조회합니다.
         */
        get: operations["getToolDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tool/{tool-id}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * tool 플랜 조회
         * @description tool의 가격 플랜을 조회합니다.
         */
        get: operations["getToolPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tool/{tool-id}/core-features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * tool 핵심 기능 조회
         * @description tool의 핵심 기능을 조회합니다.
         */
        get: operations["getToolCoreFeature"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tool/{tool-id}/blogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * tool 블로그 조회
         * @description tool 관련 블로그를 조회합니다.
         */
        get: operations["getToolBlogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tool/{tool-id}/alternatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 대안 tool 조회
         * @description 해당 tool의 대안이 되는 tool을 조회합니다.
         */
        get: operations["getRelatedTool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tool/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * tool 카테고리 조회
         * @description tool의 카테고리를 조회합니다.
         */
        get: operations["getAllCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/tool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 툴을 검색합니다
         * @description 툴 검색을 합니다
         */
        get: operations["searchTool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 게시글 검색
         * @description 게시글 검색을 합니다
         */
        get: operations["searchBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 전체 알림 목록 조회
         * @description 전체 알림을 목록으로 조회합니다.
         */
        get: operations["getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notification/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최근 알림 목록 조회
         * @description 최근 3개의 알림을 목록으로 조회합니다.
         */
        get: operations["getRecentNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notification/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE 연결
         * @description 실시간 알림을 위한 SSE(Server-Sent Events)에 연결합니다.
         */
        get: operations["subscribe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image/presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 이미지 업로드 용 presigned-url 발급
         * @description 이미지 업로드를 위한 presignedUrl을 발급합니다
         */
        get: operations["getPresignedUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 소셜 로그인 URL 반환
         * @description 소셜 로그인 URL을 반환합니다.
         */
        get: operations["requestLoginUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 관리자용 툴 조회
         * @description 관리자용 전체 툴 조회 API입니다.
         */
        get: operations["fetchAllTool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 이미지 삭제
         * @description S3 버킷에 업로드된 이미지를 삭제 합니다.
         */
        delete: operations["deleteImages"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comment/{comment-id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 댓글 삭제
         * @description 댓글을 삭제합니다.
         */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 회원 탈퇴
         * @description 회원 탈퇴를 진행합니다.
         */
        delete: operations["withdraw"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessResponseToolScrapResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ToolScrapResponse"];
        };
        ToolScrapResponse: {
            /** Format: int64 */
            toolId?: number;
            scarp?: boolean;
        };
        SuccessResponseToolLikeResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ToolLikeResponse"];
        };
        ToolLikeResponse: {
            /** Format: int64 */
            toolId?: number;
            liked?: boolean;
            /** Format: int32 */
            likeCount?: number;
        };
        /** @description 신고 생성 요청 */
        CreateReportRequest: {
            /**
             * Format: int64
             * @description 신고할 게시글의 ID (댓글 ID가 없을 경우 필수)
             * @example 1
             */
            boardId?: number;
            /**
             * Format: int64
             * @description 신고할 댓글의 ID (게시글 ID가 없을 경우 필수)
             * @example 1
             */
            commentId?: number;
            /**
             * @description 신고 유형
             * @example SPAM
             * @enum {string}
             */
            reportType: "HATE_SPEECH" | "ILLEGAL" | "SPAM" | "ADULT_CONTENT" | "POLITICAL" | "COMMERCIAL" | "DEFAMATION";
            /**
             * @description 신고 상세 내용 (선택)
             * @example 광고성 게시글입니다.
             */
            detail?: string;
            /**
             * @description 신고 제목
             * @example 광고성 게시로 인한 신고.
             */
            title: string;
            commentReport?: boolean;
        };
        /** @description 신고 생성 응답 */
        CreateReportResponse: {
            /**
             * Format: int64
             * @description 신고 ID
             */
            id?: number;
            /**
             * Format: int64
             * @description 신고자 ID
             */
            reporterId?: number;
            /** @description 신고자 닉네임 */
            reporterNickname?: string;
            /**
             * Format: int64
             * @description 신고 대상자 ID
             */
            reportedUserId?: number;
            /** @description 신고 대상자 닉네임 */
            reportedUserNickname?: string;
            /**
             * Format: int64
             * @description 신고된 게시글 ID
             */
            boardId?: number;
            /**
             * Format: int64
             * @description 신고된 댓글 ID (댓글 신고인 경우)
             */
            commentId?: number;
            /**
             * @description 신고 유형
             * @enum {string}
             */
            reportType?: "HATE_SPEECH" | "ILLEGAL" | "SPAM" | "ADULT_CONTENT" | "POLITICAL" | "COMMERCIAL" | "DEFAMATION";
            /** @description 신고 제목 */
            title?: string;
            /** @description 신고 상세 내용 */
            detail?: string;
            /**
             * Format: date-time
             * @description 생성 일시
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description 수정 일시
             */
            updatedAt?: string;
        };
        SuccessResponseCreateReportResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["CreateReportResponse"];
        };
        NoticeRequest: {
            title: string;
            url: string;
        };
        SuccessResponseVoid: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: Record<string, never>;
        };
        CommunityBlockNoticeRequest: {
            /** Format: int64 */
            userId?: number;
            blockDurationInDay?: string;
        };
        /** @description 작성할 댓글 */
        CreateCommentRequest: {
            content?: string;
            photoUrl?: string;
        };
        CreateCommentResponse: {
            /** Format: int64 */
            commentId?: number;
            content?: string;
            image?: string;
            nickname?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SuccessResponseCreateCommentResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["CreateCommentResponse"];
        };
        /** @description 수정할 게시글 */
        BoardCreateAndUpdateRequest: {
            title: string;
            content: string;
            /** Format: int64 */
            toolId?: number;
            isFree: boolean;
            imageList: string[];
        };
        BoardResponse: {
            /** Format: int64 */
            boardId?: number;
            toolName?: string;
            toolLogo?: string;
            author?: string;
            title?: string;
            content?: string;
            images?: string[];
            isScraped?: boolean;
            /** Format: int64 */
            toolId?: number;
            /** Format: int64 */
            scrapCount?: number;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int32 */
            commentCount?: number;
        };
        SuccessResponseBoardResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["BoardResponse"];
        };
        BoardScrapResponse: {
            /** Format: int64 */
            boardId?: number;
            scrap?: boolean;
        };
        SuccessResponseBoardScrapResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["BoardScrapResponse"];
        };
        SignUpRequest: {
            nickname: string;
            positions: string;
            email: string;
        };
        SignUpResponse: {
            /** Format: int64 */
            userId?: number;
            nickname?: string;
            /** @enum {string} */
            positions?: "STUDENT" | "WORKER" | "NORMAL" | "ADMIN";
            email?: string;
        };
        SuccessResponseSignUpResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["SignUpResponse"];
        };
        SuccessResponseTokenResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["TokenResponse"];
        };
        TokenResponse: {
            accessToken?: string;
        };
        SuccessResponseLong: {
            /** Format: int32 */
            status?: number;
            message?: string;
            /** Format: int64 */
            data?: number;
        };
        LoginRequest: {
            /** @enum {string} */
            socialType: "KAKAO";
        };
        LoginResponse: {
            /** Format: int64 */
            userId?: number;
            email?: string;
            isUser?: boolean;
            nickname?: string;
            /** @enum {string} */
            positions?: "STUDENT" | "WORKER" | "NORMAL" | "ADMIN";
        };
        SuccessResponseLoginResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["LoginResponse"];
        };
        /** @description 핵심 기능 목록 */
        CreateToolCoreRequest: {
            /** @description 핵심 기능명 */
            coreName?: string;
            /** @description 핵심 기능 상세 설명 */
            coreContent?: string;
        };
        /**
         * @description 플랜 목록 (배열)
         *
         *     	**사용 가이드:**
         *     	- planType에 따라 플랜 구조가 달라집니다
         *     	- 무료: 빈 배열 또는 무료 플랜 1개
         *     	- 월간: 여러 월간 구독 플랜 (예: Basic, Pro, Enterprise)
         *     	- 구매: 여러 일회성 구매 플랜 (예: Starter, Professional)
         *     	- 월간 & 연간: 월간과 연간 플랜 혼합
         *
         *     	**예시:**
         *     - 무료: [] 또는 [{"planName":"무료", "planPrice":0, "planDescription":"기본 기능 제공"}]
         *     - 월간: [{"planName":"Basic", "planPrice":10000, "planDescription":"기본 기능"},
         *     	{"planName":"Pro", "planPrice":30000, "planDescription":"고급 기능"}]
         *     - 구매: [{"planName":"Starter", "planPrice":50000, "planDescription":"시작 패키지"},
         *     	{"planName":"Professional", "planPrice":150000, "planDescription":"전문가 패키지"}]
         *     	**주의:** 각 플랜의 planName, planPrice, planDescription은 모두 필수입니다.
         */
        CreateToolPlanRequest: {
            /**
             * @description 플랜명
             * @example Basic
             */
            planName: string;
            /**
             * Format: int64
             * @description 월간 플랜 가격(원화)
             * @example 10000
             */
            priceMonthly: number;
            /**
             * Format: int64
             * @description 연간 플랜 가격(원화)
             * @example 10000
             */
            priceAnnual?: number;
            /**
             * @description 플랜 상세 설명 (최대 500자, 필수)
             * @example 기본 기능을 포함한 플랜입니다. 월 10,000원으로 이용 가능합니다.
             */
            planDescription: string;
        };
        /** @description 플랫폼 지원 정보 */
        CreateToolPlatFormRequest: {
            /** @description 웹 지원 여부 */
            supportWeb?: boolean;
            /** @description Windows 지원 여부 */
            supportWindows?: boolean;
            /** @description Mac OS 지원 여부 */
            supportMac?: boolean;
        };
        /** @description 추가할 툴 정보 (플랜 포함) */
        CreateToolRequest: {
            /** @description 영문 이름 */
            toolMainName?: string;
            /** @description 한글 이름 */
            toolSubName?: string;
            /** @description 카테고리 */
            category?: string;
            /** @description 바로가기 링크 */
            toolLink?: string;
            /** @description 한줄 소개 */
            description?: string;
            /** @description 라이센스 */
            license?: string;
            /** @description 한국어 지원 여부 */
            supportKorea?: boolean;
            /** @description 소개 글 */
            detailDescription?: string;
            /** @description 가격정책 링크 */
            planLink?: string;
            /** @description 로고 이미지 링크 */
            toolLogo?: string;
            toolPlatForm?: components["schemas"]["CreateToolPlatFormRequest"];
            /** @description 키워드 목록 */
            keywords?: string[];
            /** @description 핵심 기능 목록 */
            cores?: components["schemas"]["CreateToolCoreRequest"][];
            /**
             * @description 플랜 유형
             * @example 무료
             * @enum {string}
             */
            planType: "무료" | "월간" | "구매" | "월간 & 연간";
            /**
             * @description 플랜 목록 (배열)
             *
             *     	**사용 가이드:**
             *     	- planType에 따라 플랜 구조가 달라집니다
             *     	- 무료: 빈 배열 또는 무료 플랜 1개
             *     	- 월간: 여러 월간 구독 플랜 (예: Basic, Pro, Enterprise)
             *     	- 구매: 여러 일회성 구매 플랜 (예: Starter, Professional)
             *     	- 월간 & 연간: 월간과 연간 플랜 혼합
             *
             *     	**예시:**
             *     - 무료: [] 또는 [{"planName":"무료", "planPrice":0, "planDescription":"기본 기능 제공"}]
             *     - 월간: [{"planName":"Basic", "planPrice":10000, "planDescription":"기본 기능"},
             *     	{"planName":"Pro", "planPrice":30000, "planDescription":"고급 기능"}]
             *     - 구매: [{"planName":"Starter", "planPrice":50000, "planDescription":"시작 패키지"},
             *     	{"planName":"Professional", "planPrice":150000, "planDescription":"전문가 패키지"}]
             *     	**주의:** 각 플랜의 planName, planPrice, planDescription은 모두 필수입니다.
             */
            plans?: components["schemas"]["CreateToolPlanRequest"][];
            /** @description 블로그 링크 목록 */
            blogLinks?: string[];
            /** @description 툴 소개 이미지 링크 목록 */
            images?: string[];
            /** @description 참고하면 좋은 영상 링크 목록 */
            videos?: string[];
            /** @description 관련 툴 ID 목록 */
            relatedToolIds?: number[];
        };
        UpdateMyRequest: {
            nickname?: string;
            positions?: string;
        };
        SuccessResponseUpdateMyResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["UpdateMyResponse"];
        };
        UpdateMyResponse: {
            nickname?: string;
            /** @enum {string} */
            positions?: "STUDENT" | "WORKER" | "NORMAL" | "ADMIN";
        };
        /** @description 신고 처리 요청 */
        ProcessReportRequest: {
            /**
             * @description 처리 상태
             * @example APPROVED
             * @enum {string}
             */
            status: "PENDING" | "APPROVED" | "REJECTED";
            /**
             * @description 제재 기간
             * @example SEVEN
             * @enum {string}
             */
            suspensionDuration?: "ONE" | "THREE" | "SEVEN" | "THIRTY" | "NINETY" | "ONE_YEAR";
            /**
             * @description 처리 메모
             * @example 불건전한 게시글로 인한 제재
             */
            processNote?: string;
            /** Format: int32 */
            suspensionDays?: number;
        };
        /** @description 신고 처리 응답 */
        ProcessReportResponse: {
            /**
             * Format: int64
             * @description 신고 ID
             * @example 1
             */
            id?: number;
            /**
             * @description 처리 상태
             * @example APPROVED
             * @enum {string}
             */
            status?: "PENDING" | "APPROVED" | "REJECTED";
            /**
             * Format: int32
             * @description 제재 기간(일)
             * @example 7
             */
            suspensionDays?: number;
            /**
             * @description 제재 기간
             * @example SEVEN
             * @enum {string}
             */
            suspensionDuration?: "ONE" | "THREE" | "SEVEN" | "THIRTY" | "NINETY" | "ONE_YEAR";
            /**
             * Format: int64
             * @description 처리자 ID
             * @example 1
             */
            processedById?: number;
            /**
             * Format: date-time
             * @description 처리 일시
             */
            processedAt?: string;
            /**
             * @description 처리 메모
             * @example 불건전한 게시글로 인한 제재
             */
            processNote?: string;
        };
        SuccessResponseProcessReportResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProcessReportResponse"];
        };
        /** @description 수정 요청 DTO (플랜 정보 포함) */
        UpdateToolRequest: {
            /** @description 영문 이름 */
            toolMainName?: string;
            /** @description 한글 이름 */
            toolSubName?: string;
            /** @description 카테고리 */
            category?: string;
            /** @description 바로가기 링크 */
            toolLink?: string;
            /** @description 한줄 소개 */
            description?: string;
            /** @description 라이센스 */
            license?: string;
            /** @description 한국어 지원 여부 */
            supportKorea?: boolean;
            /** @description 소개 글 */
            detailDescription?: string;
            /** @description 가격정책 링크 */
            planLink?: string;
            /** @description 로고 이미지 링크 */
            toolLogo?: string;
            toolPlatForm?: components["schemas"]["CreateToolPlatFormRequest"];
            /** @description 키워드 목록 */
            keywords?: string[];
            /** @description 핵심 기능 목록 */
            cores?: components["schemas"]["CreateToolCoreRequest"][];
            /**
             * @description 플랜 유형
             * @example 월간
             * @enum {string}
             */
            planType: "무료" | "월간" | "구매" | "월간 & 연간";
            /**
             * @description 플랜 목록 (배열)
             *
             *     **수정 동작:**
             *     - 이 필드를 전송하면 기존 플랜들이 모두 삭제되고 새로운 플랜들로 교체됩니다
             *     - null로 보내면 플랜 정보는 변경되지 않습니다
             *     - 빈 배열([])로 보내면 모든 플랜이 삭제됩니다
             *
             *     **주의사항:**
             *     - 플랜을 수정할 때는 유지할 플랜도 포함하여 전체 플랜 목록을 다시 전송해야 합니다
             *     - planName, planPrice, planDescription이 null인 플랜은 저장되지 않습니다 (모두 필수)
             *     - planDescription은 최대 500자까지 입력 가능합니다
             *
             *     **예시:**
             *     - 플랜 추가: [{"planName":"New Plan", "planPrice":20000, "planDescription":"새로운 플랜"}]
             *     - 플랜 삭제: [] (모든 플랜 삭제)
             *     - 플랜 유지: null (기존 플랜 그대로 유지)
             *     - 플랜 수정: [수정된 전체 플랜 목록]
             */
            plans?: components["schemas"]["CreateToolPlanRequest"][];
            /** @description 블로그 링크 목록 */
            blogLinks?: string[];
            /** @description 툴 소개 이미지 링크 목록 */
            images?: string[];
            /** @description 참고하면 좋은 영상 링크 목록 */
            videos?: string[];
            /** @description 관련 툴 ID 목록 */
            relatedToolIds?: number[];
        };
        FavoriteToolsResponse: {
            toolList?: components["schemas"]["ToolDtoGetResponse"][];
        };
        SuccessResponseFavoriteToolsResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["FavoriteToolsResponse"];
        };
        ToolDtoGetResponse: {
            /** Format: int64 */
            toolId?: number;
            toolName?: string;
            toolLogo?: string;
            description?: string;
            license?: string;
            keywords?: string[];
            isScraped?: boolean;
        };
        PagenationDto: {
            /** Format: int32 */
            pageNo?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ScrapBoardsResponse: {
            /** Format: int64 */
            boardId?: number;
            toolName?: string;
            toolLogo?: string;
            author?: string;
            title?: string;
            content?: string;
            images?: string[];
            isScraped?: boolean;
            /** Format: int64 */
            toolId?: number;
            /** Format: int64 */
            scrapCount?: number;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int32 */
            commentCount?: number;
        };
        ScrapBoardsRetrieveResponse: {
            /** Format: int64 */
            userId?: number;
            boardList?: components["schemas"]["ScrapBoardsResponse"][];
            pageInfo?: components["schemas"]["PagenationDto"];
        };
        SuccessResponseScrapBoardsRetrieveResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ScrapBoardsRetrieveResponse"];
        };
        MyProfileResponse: {
            /** Format: int64 */
            userId?: number;
            nickname?: string;
            /** @enum {string} */
            positions?: "STUDENT" | "WORKER" | "NORMAL" | "ADMIN";
        };
        SuccessResponseMyProfileResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["MyProfileResponse"];
        };
        SuccessResponseBoolean: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: boolean;
        };
        BoardListResponse: {
            boardList?: components["schemas"]["BoardResponse"][];
            /** Format: int64 */
            userId?: number;
            pageInfo?: components["schemas"]["PagenationDto"];
        };
        SuccessResponseBoardListResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["BoardListResponse"];
        };
        ScrollPaginationDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int64 */
            nextCursor?: number;
        };
        SuccessResponseToolListResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ToolListResponse"];
        };
        ToolListResponse: {
            tools?: components["schemas"]["ToolResponse"][];
            scrollPaginationDto?: components["schemas"]["ScrollPaginationDto"];
        };
        ToolResponse: {
            /** Format: int64 */
            toolId?: number;
            toolName?: string;
            toolLogo?: string;
            description?: string;
            license?: string;
            keywords?: string[];
            isScraped?: boolean;
        };
        PlatformResponse: {
            Web?: boolean;
            Windows?: boolean;
            Mac?: boolean;
        };
        SuccessResponseToolDetailGetResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ToolDetailGetResponse"];
        };
        ToolDetailGetResponse: {
            /** Format: int64 */
            toolId?: number;
            toolLogo?: string;
            toolMainName?: string;
            toolSubName?: string;
            description?: string;
            license?: string;
            keywords?: string[];
            category?: string;
            toolLink?: string;
            supportKorea?: boolean;
            platform?: components["schemas"]["PlatformResponse"][];
            detailDescription?: string;
            videos?: string[];
            images?: string[];
            /** Format: date-time */
            updatedAt?: string;
            isScrapped?: boolean;
            isLiked?: boolean;
            /** Format: int32 */
            likeCount?: number;
        };
        PlanListResponse: {
            planLink?: string;
            toolPlans?: components["schemas"]["PlanResponse"][];
        };
        PlanResponse: {
            /** Format: int64 */
            planId?: number;
            planName?: string;
            /** Format: int64 */
            priceAnnual?: number;
            /** Format: int64 */
            priceMonthly?: number;
            description?: string;
        };
        SuccessResponsePlanListResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PlanListResponse"];
        };
        SuccessResponseToolCoreListResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ToolCoreListResponse"];
        };
        ToolCoreListResponse: {
            toolCoreResList?: components["schemas"]["ToolCoreResponse"][];
        };
        ToolCoreResponse: {
            /** Format: int64 */
            coreId?: number;
            coreTitle?: string;
            coreContent?: string;
        };
        SuccessResponseToolBlogListResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ToolBlogListResponse"];
        };
        ToolBlogListResponse: {
            toolBlogs?: components["schemas"]["ToolBlogResponse"][];
        };
        ToolBlogResponse: {
            /** Format: int64 */
            blogId?: number;
            blogUrl?: string;
            title?: string;
            thumbnailUrl?: string;
            summary?: string;
            siteName?: string;
            faviconUrl?: string;
        };
        RelatedToolListResponse: {
            relatedToolResList?: components["schemas"]["RelatedToolResponse"][];
        };
        RelatedToolResponse: {
            /** Format: int64 */
            toolId?: number;
            toolName?: string;
            toolLogo?: string;
            license?: string;
            keywords?: string[];
        };
        SuccessResponseRelatedToolListResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["RelatedToolListResponse"];
        };
        CategoryResponse: {
            name?: string;
            koreanName?: string;
        };
        SuccessResponseListCategoryResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["CategoryResponse"][];
        };
        SuccessResponseObject: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: Record<string, never>;
        };
        NotificationResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            content?: string;
            /** Format: int64 */
            boardId?: number;
            /** @enum {string} */
            type?: "COMMENT" | "NOTICE";
            /** Format: date-time */
            createdAt?: string;
            isRead?: boolean;
            url?: string;
        };
        SuccessResponseListNotificationResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["NotificationResponse"][];
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        PresignedUrlResponse: {
            /** @description 이미지를 업로드할 수 있는 Presigned URL */
            presignedUrl?: string;
            /** @description 업로드 완료 후 접근 가능한 Public URL */
            publicUrl?: string;
        };
        SuccessResponsePresignedUrlResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PresignedUrlResponse"];
        };
        GetCommentResponse: {
            content?: string;
            /** Format: int64 */
            commentId?: number;
            nickname?: string;
            image?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        GetCommentRetrieveResponse: {
            commentList?: components["schemas"]["GetCommentResponse"][];
            pageInfo?: components["schemas"]["ScrollPaginationDto"];
        };
        SuccessResponseGetCommentRetrieveResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["GetCommentRetrieveResponse"];
        };
        GetBoardResponse: {
            contents?: components["schemas"]["BoardResponse"][];
            scrollPaginationDto?: components["schemas"]["ScrollPaginationDto"];
            /** Format: int64 */
            nextScrapCount?: number;
        };
        SuccessResponseGetBoardResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["GetBoardResponse"];
        };
        SuccessResponseString: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: string;
        };
        AdminToolPageResponse: {
            tools?: components["schemas"]["ToolResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
        };
        SuccessResponseAdminToolPageResponse: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AdminToolPageResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postToolScrap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description tool Id
                 * @example 1
                 */
                "tool-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseToolScrapResponse"];
                };
            };
        };
    };
    postToolLike: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description tool Id
                 * @example 1
                 */
                "tool-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseToolLikeResponse"];
                };
            };
        };
    };
    createReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseCreateReportResponse"];
                };
            };
        };
    };
    notice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoticeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseVoid"];
                };
            };
        };
    };
    blockNotice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommunityBlockNoticeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseVoid"];
                };
            };
        };
    };
    getComment: {
        parameters: {
            query: {
                /**
                 * @description board Id
                 * @example 1
                 */
                "board-id": number;
                /**
                 * @description 조회할 댓글 개수
                 * @example 10
                 */
                size?: number;
                /**
                 * @description 조회했을 때 마지막 comment Id
                 * @example 10
                 */
                lastCommentId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseGetCommentRetrieveResponse"];
                };
            };
        };
    };
    postComment: {
        parameters: {
            query: {
                /**
                 * @description board Id
                 * @example 1
                 */
                "board-id": number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseCreateCommentResponse"];
                };
            };
        };
    };
    getBoardList: {
        parameters: {
            query?: {
                /**
                 * @description 자유 게시판 게시글 여부
                 * @example true
                 */
                noTopic?: boolean;
                /**
                 * @description tool Id
                 * @example 1
                 */
                toolId?: number;
                /**
                 * @description 조회할 게시글 개수
                 * @example 10
                 */
                size?: number;
                /**
                 * @description 조회했을 때 마지막 board Id
                 * @example 10
                 */
                lastBoardId?: number;
                /**
                 * @description 정렬 기준 (LATEST: 최신순, SCRAP: 스크랩 많은 순)
                 * @example LATEST
                 */
                sortBy?: string;
                /**
                 * @description 스크랩 정렬 시 마지막 게시글의 스크랩 수 (sortBy=SCRAP일 때 필요)
                 * @example 5
                 */
                lastScrapCount?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseGetBoardResponse"];
                };
            };
        };
    };
    createBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardCreateAndUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseBoardResponse"];
                };
            };
        };
    };
    scrapBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description board Id
                 * @example 1
                 */
                "board-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseBoardScrapResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseSignUpResponse"];
                };
            };
        };
    };
    reissueToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseTokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseLong"];
                };
            };
        };
    };
    login: {
        parameters: {
            query: {
                /**
                 * @description Authorization Code
                 * @example 1234
                 */
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseLoginResponse"];
                };
            };
        };
    };
    createTool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateToolRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseVoid"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseMyProfileResponse"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseUpdateMyResponse"];
                };
            };
        };
    };
    processReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 신고 ID */
                reportId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessReportRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseProcessReportResponse"];
                };
            };
        };
    };
    readNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description notification Id
                 * @example 1
                 */
                "notification-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseVoid"];
                };
            };
        };
    };
    getBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description board Id
                 * @example 1
                 */
                "board-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseBoardResponse"];
                };
            };
        };
    };
    deleteBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description board Id
                 * @example 1
                 */
                "board-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseVoid"];
                };
            };
        };
    };
    updateBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description board Id
                 * @example 1
                 */
                "board-id": number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardCreateAndUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseBoardResponse"];
                };
            };
        };
    };
    deleteTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 삭제 할 툴 ID */
                toolId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseVoid"];
                };
            };
        };
    };
    updateTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 수정할 툴 ID */
                toolId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateToolRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseVoid"];
                };
            };
        };
    };
    getFavoriteTools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseFavoriteToolsResponse"];
                };
            };
        };
    };
    getScrapBoards: {
        parameters: {
            query?: {
                /**
                 * @description 조회할 페이지
                 * @example 1
                 */
                page?: number;
                /**
                 * @description 조회할 게시글 개수
                 * @example 5
                 */
                size?: number;
                /**
                 * @description 정렬 기준
                 * @example createdAt
                 */
                criteria?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseScrapBoardsRetrieveResponse"];
                };
            };
        };
    };
    checkDuplicate: {
        parameters: {
            query: {
                /**
                 * @description 닉네임
                 * @example test
                 */
                nickname: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseBoolean"];
                };
            };
        };
    };
    getUserBoards: {
        parameters: {
            query?: {
                /**
                 * @description 조회할 페이지
                 * @example 1
                 */
                page?: number;
                /**
                 * @description 조회할 게시글 개수
                 * @example 5
                 */
                size?: number;
                /**
                 * @description 정렬 기준
                 * @example createdAt
                 */
                criteria?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseBoardListResponse"];
                };
            };
        };
    };
    getToolList: {
        parameters: {
            query: {
                /**
                 * @description 정렬 기준
                 * @example popular
                 */
                criteria?: string;
                /**
                 * @description 카테고리(영어)
                 * @example ALL
                 */
                category?: string;
                /**
                 * @description 조회할 tool의 개수
                 * @example 18
                 */
                size?: number;
                /**
                 * @description 조회했을 때 마지막 tool Id
                 * @example 18
                 */
                lastToolId?: number;
                /**
                 * @description 무료 tool 여부
                 * @example true
                 */
                isFree: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseToolListResponse"];
                };
            };
        };
    };
    getToolDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description tool Id
                 * @example 1
                 */
                "tool-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseToolDetailGetResponse"];
                };
            };
        };
    };
    getToolPlans: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description tool Id
                 * @example 1
                 */
                "tool-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponsePlanListResponse"];
                };
            };
        };
    };
    getToolCoreFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description tool Id
                 * @example 1
                 */
                "tool-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseToolCoreListResponse"];
                };
            };
        };
    };
    getToolBlogs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description tool Id
                 * @example 1
                 */
                "tool-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseToolBlogListResponse"];
                };
            };
        };
    };
    getRelatedTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description tool Id
                 * @example 1
                 */
                "tool-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseRelatedToolListResponse"];
                };
            };
        };
    };
    getAllCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseListCategoryResponse"];
                };
            };
        };
    };
    searchTool: {
        parameters: {
            query: {
                keyword: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseObject"];
                };
            };
        };
    };
    searchBoard: {
        parameters: {
            query: {
                keyword: string;
                nextCursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseObject"];
                };
            };
        };
    };
    getNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseListNotificationResponse"];
                };
            };
        };
    };
    getRecentNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseListNotificationResponse"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description EventStream이 끊어 젔을 경우, Web에서 수신한 마지막 ID 값
                 * @example 2_1747732045603
                 */
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    getPresignedUrl: {
        parameters: {
            query: {
                /**
                 * @description 이미지가 저장될 디렉토리(prefix) (예: profile, board)
                 * @example board
                 */
                prefix?: string;
                /**
                 * @description 파일 확장자 (예: .jpg, .png)
                 * @example .png
                 */
                extension: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponsePresignedUrlResponse"];
                };
            };
        };
    };
    requestLoginUrl: {
        parameters: {
            query: {
                /**
                 * @description 소셜 로그인 타입
                 * @example KAKAO
                 */
                socialType: "KAKAO";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseString"];
                };
            };
        };
    };
    fetchAllTool: {
        parameters: {
            query?: {
                /**
                 * @description 정렬 기준
                 * @example createdAt
                 */
                criteria?: string;
                /**
                 * @description 정렬 순서 (ASC/DESC)
                 * @example DESC
                 */
                direction?: string;
                /**
                 * @description 페이지 인덱스
                 * @example 0
                 */
                page?: number;
                /**
                 * @description 페이지 크기
                 * @example 10
                 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseAdminToolPageResponse"];
                };
            };
        };
    };
    deleteImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": number[];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number[];
                };
            };
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description comment Id
                 * @example 1
                 */
                "comment-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseVoid"];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseVoid"];
                };
            };
        };
    };
}
